import type { Metadata } from "next";
import "./globals.css";
import VisualEditsMessenger from "../visual-edits/VisualEditsMessenger";
import ErrorReporter from "@/components/ErrorReporter";
import Script from "next/script";
import Link from "next/link";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <ErrorReporter />
        <Script
          src="https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/scripts//route-messenger.js"
          strategy="afterInteractive"
          data-target-origin="*"
          data-message-type="ROUTE_CHANGE"
          data-include-search-params="true"
          data-only-in-iframe="true"
          data-debug="true"
          data-custom-data='{"appName": "YourApp", "version": "1.0.0", "greeting": "hi"}'
        />
        <header className="sticky top-0 z-50 bg-background/80 backdrop-blur border-b">
          <div className="max-w-6xl mx-auto px-4 py-3 flex items-center justify-between">
            <Link href="/" className="font-semibold text-lg">
              IndiFusion Wear
            </Link>
            <nav className="flex items-center gap-6">
              <Link href="/avatar" className="text-sm text-muted-foreground hover:text-foreground">
                Avatar
              </Link>
              <Link href="/catalog" className="text-sm text-muted-foreground hover:text-foreground">
                Catalog
              </Link>
              <Link href="/preview" className="text-sm text-muted-foreground hover:text-foreground">
                Preview
              </Link>
              <Link href="/cart" className="text-sm text-muted-foreground hover:text-foreground">
                Cart
              </Link>
              <Link href="/login" className="text-sm text-muted-foreground hover:text-foreground">
                Login
              </Link>
              <Link
                href="/register"
                className="text-sm rounded-md bg-primary text-primary-foreground px-3 py-1.5 hover:bg-primary/90"
              >
                Register
              </Link>
            </nav>
          </div>
        </header>
        <Toaster position="top-right" richColors />
        {children}
        <VisualEditsMessenger />
      </body>
    </html>
  );
}