import { db } from '@/db';
import { garments } from '@/db/schema';

async function main() {
    // Delete all existing records first
    await db.delete(garments);
    console.log('🗑️  Cleared existing garments data');

    const currentTimestamp = new Date().toISOString();

    const sampleGarments = [
        {
            name: 'Banarasi Silk Saree',
            type: 'saree',
            description: 'Exquisite Banarasi silk woven by master artisans of Varanasi, featuring intricate gold zari work that captures centuries of textile heritage. This luxurious drape showcases timeless elegance with traditional brocade patterns, perfect for weddings and grand celebrations.',
            imageUrl: 'https://placehold.co/400x600/D4AF37/FFFFFF?text=Banarasi+Silk+Saree',
            price: 375.00,
            category: 'women',
            measurements: null,
            qualityRating: null,
            history: null,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            name: 'Anarkali Suit',
            type: 'anarkali',
            description: 'Regal Anarkali suit adorned with delicate thread embroidery and mirror work, inspired by Mughal court aesthetics. The flowing silhouette features contemporary cuts while honoring traditional craftsmanship, ideal for festive occasions and formal gatherings.',
            imageUrl: 'https://placehold.co/400x600/D4AF37/FFFFFF?text=Anarkali+Suit',
            price: 225.00,
            category: 'women',
            measurements: null,
            qualityRating: null,
            history: null,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            name: 'Traditional Lehenga Choli',
            type: 'lehenga-choli',
            description: 'Opulent lehenga choli crafted with hand-embroidered sequins and traditional gota patti work, showcasing the artistry of Rajasthani craftsmen. This three-piece ensemble features rich fabrics and intricate detailing, perfect for weddings and ceremonial events.',
            imageUrl: 'https://placehold.co/400x600/D4AF37/FFFFFF?text=Traditional+Lehenga+Choli',
            price: 350.00,
            category: 'women',
            measurements: null,
            qualityRating: null,
            history: null,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            name: 'Chanderi Silk Dupatta',
            type: 'dupatta',
            description: 'Lightweight Chanderi silk dupatta from Madhya Pradesh, featuring traditional coin motifs and delicate zari borders. This handwoven masterpiece showcases the region\'s 700-year-old weaving heritage, adding grace and elegance to any ethnic ensemble.',
            imageUrl: 'https://placehold.co/400x600/D4AF37/FFFFFF?text=Chanderi+Silk+Dupatta',
            price: 165.00,
            category: 'women',
            measurements: null,
            qualityRating: null,
            history: null,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            name: 'Designer Sharara Set',
            type: 'sharara',
            description: 'Contemporary sharara set featuring flowing palazzo-style bottoms with intricate embroidery and modern tailoring. This elegant ensemble combines Lucknowi craftsmanship with contemporary design sensibilities, perfect for festive celebrations and special occasions.',
            imageUrl: 'https://placehold.co/400x600/D4AF37/FFFFFF?text=Designer+Sharara+Set',
            price: 300.00,
            category: 'women',
            measurements: null,
            qualityRating: null,
            history: null,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            name: 'Bandhani Print Saree',
            type: 'saree',
            description: 'Vibrant Bandhani saree showcasing the traditional tie-dye art of Gujarat and Rajasthan, created through meticulous hand-tying and natural dyeing processes. Each intricate dot pattern represents centuries of artisan expertise, ideal for festivals and cultural celebrations.',
            imageUrl: 'https://placehold.co/400x600/D4AF37/FFFFFF?text=Bandhani+Print+Saree',
            price: 200.00,
            category: 'women',
            measurements: null,
            qualityRating: null,
            history: null,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            name: 'Embroidered Palazzo Suit',
            type: 'palazzo-suit',
            description: 'Modern palazzo suit featuring hand-embroidered yoke and flowing wide-leg pants, blending comfort with traditional elegance. This versatile ensemble showcases contemporary silhouettes with classic Indian embellishment techniques, suitable for formal events and gatherings.',
            imageUrl: 'https://placehold.co/400x600/D4AF37/FFFFFF?text=Embroidered+Palazzo+Suit',
            price: 155.00,
            category: 'women',
            measurements: null,
            qualityRating: null,
            history: null,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            name: 'Hand-embroidered Kurta Set',
            type: 'kurta-set',
            description: 'Hand-embroidered kurta set crafted with meticulous attention to detail, blending traditional chikankari motifs with contemporary silhouettes. This elegant ensemble features fine cotton fabric and intricate threadwork, ideal for festive occasions and formal gatherings.',
            imageUrl: 'https://placehold.co/400x600/D4AF37/FFFFFF?text=Hand-embroidered+Kurta+Set',
            price: 135.00,
            category: 'men',
            measurements: null,
            qualityRating: null,
            history: null,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            name: 'Royal Sherwani',
            type: 'sherwani',
            description: 'Majestic sherwani adorned with gold thread embroidery and traditional zardozi work, reflecting the grandeur of Mughal royal courts. This statement piece features impeccable tailoring and rich embellishments, perfect for weddings and ceremonial occasions.',
            imageUrl: 'https://placehold.co/400x600/D4AF37/FFFFFF?text=Royal+Sherwani',
            price: 400.00,
            category: 'men',
            measurements: null,
            qualityRating: null,
            history: null,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            name: 'Cotton Kurta Pajama',
            type: 'kurta-pajama',
            description: 'Classic cotton kurta pajama set featuring breathable handloom fabric and minimalist design, embodying traditional comfort with modern aesthetics. This versatile ensemble showcases clean lines and subtle detailing, suitable for daily wear and casual gatherings.',
            imageUrl: 'https://placehold.co/400x600/D4AF37/FFFFFF?text=Cotton+Kurta+Pajama',
            price: 100.00,
            category: 'men',
            measurements: null,
            qualityRating: null,
            history: null,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            name: 'Velvet Nehru Jacket',
            type: 'nehru-jacket',
            description: 'Sophisticated velvet Nehru jacket featuring closed collar design and subtle brocade patterns, inspired by Pandit Nehru\'s iconic style. This timeless piece combines Eastern aesthetics with Western tailoring precision, perfect for formal events and elegant soirees.',
            imageUrl: 'https://placehold.co/400x600/D4AF37/FFFFFF?text=Velvet+Nehru+Jacket',
            price: 175.00,
            category: 'men',
            measurements: null,
            qualityRating: null,
            history: null,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            name: 'Silk Blend Bandhgala',
            type: 'nehru-jacket',
            description: 'Luxurious silk blend bandhgala featuring traditional button detailing and contemporary slim-fit silhouette. This regal jacket showcases the sophistication of Indian formal wear with impeccable craftsmanship, ideal for weddings and distinguished gatherings.',
            imageUrl: 'https://placehold.co/400x600/D4AF37/FFFFFF?text=Silk+Blend+Bandhgala',
            price: 220.00,
            category: 'men',
            measurements: null,
            qualityRating: null,
            history: null,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            name: 'Kids Ethnic Ensemble',
            type: 'ethnic-ensemble',
            description: 'Charming ethnic ensemble for children featuring comfortable cotton fabric with traditional embroidery and playful motifs. This adorable outfit combines cultural heritage with child-friendly design, perfect for festivals and family celebrations.',
            imageUrl: 'https://placehold.co/400x600/D4AF37/FFFFFF?text=Kids+Ethnic+Ensemble',
            price: 90.00,
            category: 'kids',
            measurements: null,
            qualityRating: null,
            history: null,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            name: 'Kids Sherwani Set',
            type: 'sherwani',
            description: 'Miniature sherwani set designed for young gentlemen, featuring intricate embroidery and comfortable fit with elastic adjustments. This elegant ensemble mirrors traditional adult designs while ensuring ease of movement, ideal for weddings and special occasions.',
            imageUrl: 'https://placehold.co/400x600/D4AF37/FFFFFF?text=Kids+Sherwani+Set',
            price: 125.00,
            category: 'kids',
            measurements: null,
            qualityRating: null,
            history: null,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
        {
            name: 'Kids Lehenga Choli',
            type: 'lehenga-choli',
            description: 'Delightful lehenga choli for young girls featuring vibrant colors, playful embellishments, and comfortable cotton lining. This traditional outfit showcases age-appropriate design with twirl-worthy skirts and secure fittings, perfect for festive celebrations.',
            imageUrl: 'https://placehold.co/400x600/D4AF37/FFFFFF?text=Kids+Lehenga+Choli',
            price: 107.50,
            category: 'kids',
            measurements: null,
            qualityRating: null,
            history: null,
            createdAt: currentTimestamp,
            updatedAt: currentTimestamp,
        },
    ];

    await db.insert(garments).values(sampleGarments);

    console.log('✅ Garments seeder completed successfully - 15 Indian heritage products added');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});